### ISSUE TITLE
Inconsistent Naming Scheme (eg: LevelDatastore vs DatastoreLevel)

### ISSUE THREAD

**Issue by wellcaffeinated** [ipfs/js-stores#229]
The naming conventions of various stores seem to be inconsistent depending on whether they are loaded via script tag (unpkg) or module import.

For example, datastore-level is exported as `LevelDatastore`
https://github.com/ipfs/js-stores/blob/eb59834bfb29a7b61fb361ae2ecc90d3d19b908b/packages/datastore-level/src/index.ts#L26
However if using a script tag it is `DatastoreLevel`.

I'd be happy to submit pull requests, but some convention should be decided :)

**Comment by achingbrain** [comment]
The script tag global export is derived from the module name, the exported class is not.  They are at least consistently inconsistent.

Our publishing of minified script versions pre-dates exports maps so needs a bit of a rethink anyway since only the root export is bundled.

This conversation would happen on the https://github.com/ipfs/aegir repo and not here, since that's where the bundling code is.
